# https://github.com/HugoDF/express-postgres-starter
version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@localhost:5432/sandbox
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
    command: yarn start
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sandbox
